version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/local/apache2/htdocs/
    container_name: motorized-schedule
    restart: unless-stopped
    volumes:
      - ./:/usr/local/apache2/htdocs/
    ports:
      - "8080:80"